spring.application.name=Weather-App


weather.api.key=ec0fdff73c63461fbc6100915262302
weather.api.url=http://api.weatherapi.com/v1/current.json
weather.api.forcast.url=http://api.weatherapi.com/v1/forecast.json